import schedule
import time
from Exec import enviar_msg
from Projetos.Guia.app1 import enviar_guia
from Projetos.Rotina.Main import main
from Projetos.Bot_Whatsapp_WHATKIT.Down_Notas_Emitidas import down_notas

schedule.every().monday.at("08:00").do(enviar_msg)
schedule.every().monday.at("09:00").do(enviar_msg)
schedule.every().monday.at("09:30").do(main)
schedule.every().monday.at("10:00").do(enviar_msg)
schedule.every().monday.at("11:00").do(enviar_msg)
schedule.every().monday.at("12:00").do(enviar_msg)
schedule.every().monday.at("12:15").do(down_notas)
schedule.every().monday.at("13:00").do(enviar_msg)
schedule.every().monday.at("14:00").do(enviar_msg)
schedule.every().monday.at("15:00").do(enviar_msg)
schedule.every().monday.at("15:30").do(enviar_guia)
schedule.every().monday.at("16:00").do(enviar_msg)
schedule.every().monday.at("17:00").do(enviar_msg)
schedule.every().monday.at("18:00").do(enviar_msg)
schedule.every().monday.at("23:00").do(down_notas)

schedule.every().tuesday.at("08:00").do(enviar_msg)
schedule.every().tuesday.at("09:00").do(enviar_msg)
schedule.every().tuesday.at("09:30").do(main)
schedule.every().tuesday.at("10:00").do(enviar_msg)
schedule.every().tuesday.at("11:00").do(enviar_msg)
schedule.every().tuesday.at("12:00").do(enviar_msg)
schedule.every().tuesday.at("12:15").do(down_notas)
schedule.every().tuesday.at("13:00").do(enviar_msg)
schedule.every().tuesday.at("14:00").do(enviar_msg)
schedule.every().tuesday.at("15:00").do(enviar_msg)
schedule.every().tuesday.at("15:30").do(enviar_guia)
schedule.every().tuesday.at("16:00").do(enviar_msg)
schedule.every().tuesday.at("17:00").do(enviar_msg)
schedule.every().tuesday.at("18:00").do(enviar_msg)
schedule.every().tuesday.at("23:00").do(down_notas)

schedule.every().wednesday.at("08:00").do(enviar_msg)
schedule.every().wednesday.at("09:00").do(enviar_msg)
schedule.every().wednesday.at("09:30").do(main)
schedule.every().wednesday.at("10:00").do(enviar_msg)
schedule.every().wednesday.at("11:00").do(enviar_msg)
schedule.every().wednesday.at("12:00").do(enviar_msg)
schedule.every().wednesday.at("12:15").do(down_notas)
schedule.every().wednesday.at("13:00").do(enviar_msg)
schedule.every().wednesday.at("14:00").do(enviar_msg)
schedule.every().wednesday.at("15:00").do(enviar_msg)
schedule.every().wednesday.at("15:30").do(enviar_guia)
schedule.every().wednesday.at("16:00").do(enviar_msg)
schedule.every().wednesday.at("17:00").do(enviar_msg)
schedule.every().wednesday.at("18:00").do(enviar_msg)
schedule.every().wednesday.at("23:00").do(down_notas)

schedule.every().thursday.at("08:00").do(enviar_msg)
schedule.every().thursday.at("09:00").do(enviar_msg)
schedule.every().thursday.at("09:30").do(main)
schedule.every().thursday.at("10:00").do(enviar_msg)
schedule.every().thursday.at("11:00").do(enviar_msg)
schedule.every().thursday.at("12:00").do(enviar_msg)
schedule.every().thursday.at("12:15").do(down_notas)
schedule.every().thursday.at("13:00").do(enviar_msg)
schedule.every().thursday.at("14:00").do(enviar_msg)
schedule.every().thursday.at("15:00").do(enviar_msg)
schedule.every().thursday.at("15:30").do(enviar_guia)
schedule.every().thursday.at("16:00").do(enviar_msg)
schedule.every().thursday.at("17:00").do(enviar_msg)
schedule.every().thursday.at("18:00").do(enviar_msg)
schedule.every().thursday.at("23:00").do(down_notas)

schedule.every().friday.at("08:00").do(enviar_msg)
schedule.every().friday.at("09:00").do(enviar_msg)
schedule.every().friday.at("09:30").do(main)
schedule.every().friday.at("10:00").do(enviar_msg)
schedule.every().friday.at("11:00").do(enviar_msg)
schedule.every().friday.at("12:00").do(enviar_msg)
schedule.every().friday.at("12:15").do(down_notas)
schedule.every().friday.at("13:00").do(enviar_msg)
schedule.every().friday.at("14:00").do(enviar_msg)
schedule.every().friday.at("15:00").do(enviar_msg)
schedule.every().friday.at("15:30").do(enviar_guia)
schedule.every().friday.at("16:00").do(enviar_msg)
schedule.every().friday.at("17:00").do(enviar_msg)
schedule.every().friday.at("18:00").do(enviar_msg)
schedule.every().friday.at("23:00").do(down_notas)

while True:
    schedule.run_pending()
    time.sleep(1)
